server:
  port: 8080
spring:
  application:
    name: test
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        slave_1:
          url: jdbc:postgresql://localhost:5432/postgres
          driver-class-name: org.postgresql.Driver
          username: postgres
          password: postgres
mybatis-plus:
  mapper-locations: classpath*:/mybatis.mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  type-handlers-package: com.seven.mybatis.typehandler
#  type-enums-package: com.seven.spring.enums
#logging:
#  config: classpath:logback.xml
